(*<pointer.pas>
 * Pointer functions to turn Turbo Pascal 3 more flexible with
 * modern pointer operations, present in newer Delphi releases.
 * CopyLeft (c) since 1995 by PopolonY2k.
 *)

(**
  *
  * $Id: $
  * $Author: $
  * $Date: $
  * $Revision: $
  * $HeadURL: $
  *)

(*
 * This module depends on folowing include files (respect the order):
 * - types.pas
 *)


(**
  * Increment the pointer address using the units passed by parameter.
  * @param pPointer The pointer that address will be incremented;
  * @param nIncrement The increment to skip to thew new address;
  *)
Function IncPtr( pPointer : Pointer; nIncrement : Integer ) : Pointer;
Begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   *)
  Inline( $2A/pPointer         { LD  HL,(pPointer)     }
          /$ED/$5B/nIncrement  { LD  DE,(nIncrement)   }
          /$19                 { ADD HL,DE             }
          /$22/pPointer        { LD  (pPointer),HL     } );
  IncPtr := pPointer;
End;
